"""v_1_change phone number column

Revision ID: 844c371d0d78
Revises: 7f8aea1e75d8
Create Date: 2024-02-08 16:23:29.187899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '844c371d0d78'
down_revision: Union[str, None] = '7f8aea1e75d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone_no',
               existing_type=sa.INTEGER(),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone_no',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
