"""v 2 create post story like comment tables

Revision ID: 7f021649b6bd
Revises: 844c371d0d78
Create Date: 2024-03-11 14:40:30.718429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f021649b6bd'
down_revision: Union[str, None] = '844c371d0d78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Post',
    sa.Column('id', sa.VARCHAR(length=256), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=256), nullable=True),
    sa.Column('photo', sa.VARCHAR(length=255), nullable=True),
    sa.Column('description', sa.VARCHAR(length=30), nullable=True),
    sa.Column('location', sa.VARCHAR(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Story',
    sa.Column('id', sa.String(length=256), nullable=False),
    sa.Column('photo', sa.String(length=256), nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Comments',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('post_id', sa.VARCHAR(length=256), nullable=True),
    sa.Column('comment', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['Post.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Like',
    sa.Column('id', sa.VARCHAR(length=256), nullable=False),
    sa.Column('post_id', sa.VARCHAR(length=256), nullable=True),
    sa.Column('count', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['Post.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Like')
    op.drop_table('Comments')
    op.drop_table('Story')
    op.drop_table('Post')
    # ### end Alembic commands ###
